# Generated by Django 5.2 on 2026-07-30 13:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import phone_field.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("HOUSE_OWNER", "House Owner"),
                            ("CARETAKER", "Caretaker"),
                            ("TENANT", "Tenant"),
                            ("GUEST", "Guest"),
                        ],
                        default="GUEST",
                        max_length=20,
                    ),
                ),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        blank=True, help_text="Contact phone number", max_length=31
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_phone_verified", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("IN_REVIEW", "In Review"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verification_documents", models.JSONField(blank=True, default=list)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("timezone", models.CharField(default="Africa/Nairobi", max_length=50)),
                (
                    "notification_preferences",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("is_suspicious", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "login_history",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="OwnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "company_registration_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("tax_pin", models.CharField(blank=True, max_length=50)),
                (
                    "business_license",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/business_licenses/"
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("FREE_TRIAL", "Free Trial"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="FREE_TRIAL",
                        max_length=20,
                    ),
                ),
                ("subscription_start", models.DateTimeField(auto_now_add=True)),
                ("subscription_end", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic"),
                            ("PREMIUM", "Premium"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        default="BASIC",
                        max_length=50,
                    ),
                ),
                ("total_properties", models.IntegerField(default=0)),
                ("total_tenants", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "owner_profiles",
            },
        ),
        migrations.CreateModel(
            name="TenantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employer_name", models.CharField(blank=True, max_length=200)),
                (
                    "employer_contact",
                    phone_field.models.PhoneField(blank=True, max_length=31),
                ),
                ("job_title", models.CharField(blank=True, max_length=100)),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("guarantor_name", models.CharField(blank=True, max_length=200)),
                (
                    "guarantor_phone",
                    phone_field.models.PhoneField(blank=True, max_length=31),
                ),
                ("guarantor_email", models.EmailField(blank=True, max_length=254)),
                ("guarantor_relationship", models.CharField(blank=True, max_length=50)),
                ("previous_rental_address", models.TextField(blank=True)),
                (
                    "previous_landlord_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "previous_landlord_phone",
                    phone_field.models.PhoneField(blank=True, max_length=31),
                ),
                (
                    "previous_rental_duration",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "national_id",
                    models.FileField(blank=True, null=True, upload_to="documents/ids/"),
                ),
                (
                    "passport_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/passports/"
                    ),
                ),
                (
                    "employment_letter",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/employment/"
                    ),
                ),
                (
                    "bank_statement",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/bank/"
                    ),
                ),
                ("reference_name", models.CharField(blank=True, max_length=200)),
                (
                    "reference_phone",
                    phone_field.models.PhoneField(blank=True, max_length=31),
                ),
                ("reference_email", models.EmailField(blank=True, max_length=254)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenant_profiles",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Kenya", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("business_name", models.CharField(blank=True, max_length=200)),
                ("business_registration", models.CharField(blank=True, max_length=100)),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    phone_field.models.PhoneField(blank=True, max_length=31),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone"),
                            ("SMS", "SMS"),
                        ],
                        default="EMAIL",
                        max_length=20,
                    ),
                ),
                ("marketing_opt_in", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "user_type"], name="users_email_e7d39f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["verification_status"], name="users_verific_ff7924_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ownerprofile",
            index=models.Index(
                fields=["subscription_status", "subscription_end"],
                name="owner_profi_subscri_46d577_idx",
            ),
        ),
    ]
