# Generated by Django 5.2 on 2026-08-03 10:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_caretakerprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaystackSubaccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(help_text="Paystack bank code", max_length=10),
                ),
                ("account_number", models.CharField(max_length=20)),
                ("account_name", models.CharField(max_length=200)),
                ("subaccount_code", models.CharField(max_length=100, unique=True)),
                ("business_name", models.CharField(max_length=200)),
                (
                    "percentage_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        help_text="Percentage charge for Winda (owner gets 97%)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("paystack_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "paystack_subaccounts",
            },
        ),
        migrations.RemoveIndex(
            model_name="ownerprofile",
            name="owner_profi_subscri_46d577_idx",
        ),
        migrations.RenameField(
            model_name="ownerprofile",
            old_name="subscription_start",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="ownerprofile",
            name="subscription_end",
        ),
        migrations.RemoveField(
            model_name="ownerprofile",
            name="subscription_plan",
        ),
        migrations.RemoveField(
            model_name="ownerprofile",
            name="subscription_status",
        ),
        migrations.AddField(
            model_name="ownerprofile",
            name="bank_account_set_up",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ownerprofile",
            name="paystack_subaccount_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ownerprofile",
            name="platform_fees_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="ownerprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="paystacksubaccount",
            name="owner_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paystack_subaccount",
                to="accounts.ownerprofile",
            ),
        ),
    ]
