# Generated by Django 5.2 on 2024-08-12
from django.db import migrations
from django.contrib.auth.hashers import make_password
import os

def create_superadmin(apps, schema_editor):
    """Create superadmin account if it doesn't exist"""
    User = apps.get_model('accounts', 'User')
    
    # Check if superadmin already exists
    if User.objects.filter(is_superuser=True).exists():
        print('Superadmin already exists. Skipping creation.')
        return
    
    # Get superadmin credentials from environment variables or use defaults
    email = os.getenv('SUPERADMIN_EMAIL', 'windaafricasupport@gmail.com')
    password = os.getenv('SUPERADMIN_PASSWORD', 'Admin@12345')
    first_name = os.getenv('SUPERADMIN_FIRST_NAME', 'Winda')
    last_name = os.getenv('SUPERADMIN_LAST_NAME', 'Africa')
    
    # Create superadmin
    User.objects.create(
        email=email,
        username=email,  # Using email as username
        first_name=first_name,
        last_name=last_name,
        password=make_password(password),
        is_superuser=True,
        is_staff=True,
        is_active=True,
        user_type='SUPER_ADMIN',
        is_email_verified=True,
        verification_status='VERIFIED'
    )
    
    print(f'Superadmin created successfully!')
    print(f'Email: {email}')
    print(f'Password: {password}')
    print('Please change the password after first login.')


def delete_superadmin(apps, schema_editor):
    """Delete superadmin (for rollback)"""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email='windaafricasupport@gmail.com', is_superuser=True).delete()
    print('Superadmin deleted.')


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_paystacksubaccount_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superadmin, delete_superadmin),
    ]