# Generated by Django 5.2 on 2026-08-18 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_create_superadmin"),
        (
            "properties",
            "0011_alter_property_bathrooms_alter_property_bedrooms_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caretakerprofile",
            name="assigned_properties",
        ),
        migrations.AlterField(
            model_name="caretakerprofile",
            name="permission_level",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic - View Only"),
                    ("STANDARD", "Standard - View & Respond"),
                    ("FULL", "Full - Manage Properties"),
                ],
                default="BASIC",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CaretakerPropertyAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "caretaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_assignments",
                        to="accounts.caretakerprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caretaker_assignments",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "caretaker_property_assignments",
                "unique_together": {("caretaker", "property")},
            },
        ),
    ]
