# Generated by Django 5.2 on 2026-08-20 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_caretakerprofile_assigned_properties_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_step",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
