# Generated by Django 5.2.11 on 2026-09-16 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_admin_notes_user_registration_step_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("HOUSE_OWNER", "House Owner"),
                    ("CARETAKER", "Caretaker"),
                    ("PROPERTY_SCOUT", "Property Scout"),
                    ("TENANT", "Tenant"),
                    ("GUEST", "Guest"),
                ],
                default="GUEST",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ScoutProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_or_agent_id", models.CharField(blank=True, max_length=100)),
                ("payout_account_name", models.CharField(blank=True, max_length=200)),
                ("payout_account_number", models.CharField(blank=True, max_length=50)),
                ("payout_bank_code", models.CharField(blank=True, max_length=20)),
                (
                    "payout_paystack_subaccount",
                    models.CharField(blank=True, max_length=100),
                ),
                ("total_properties_listed", models.PositiveIntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scout_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scout_profiles",
            },
        ),
    ]
