# Generated by Django 5.2 on 2026-10-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_user_user_type_scoutprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoutprofile",
            name="payout_paystack_recipient_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
