# Generated by Django 5.2 on 2026-07-30 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Apartment"),
                            ("BUNGALOW", "Bungalow"),
                            ("MAISONETTE", "Maisonette"),
                            ("DUPLEX", "Duplex"),
                            ("PENTHOUSE", "Penthouse"),
                            ("STUDIO", "Studio"),
                            ("TOWNHOUSE", "Townhouse"),
                            ("COMMERCIAL", "Commercial"),
                            ("LAND", "Land"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "furnishing_status",
                    models.CharField(
                        choices=[
                            ("FURNISHED", "Furnished"),
                            ("SEMI_FURNISHED", "Semi-Furnished"),
                            ("UNFURNISHED", "Unfurnished"),
                        ],
                        default="UNFURNISHED",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="Kenya", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("rental_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "service_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("negotiation_allowed", models.BooleanField(default=False)),
                ("bedrooms", models.PositiveIntegerField()),
                ("bathrooms", models.PositiveIntegerField()),
                ("parking_spaces", models.PositiveIntegerField(default=0)),
                ("square_feet", models.PositiveIntegerField(blank=True, null=True)),
                ("floor_number", models.PositiveIntegerField(blank=True, null=True)),
                ("total_floors", models.PositiveIntegerField(blank=True, null=True)),
                ("year_built", models.PositiveIntegerField(blank=True, null=True)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("features", models.JSONField(blank=True, default=list)),
                (
                    "main_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="properties/main/"
                    ),
                ),
                ("images", models.JSONField(blank=True, default=list)),
                ("video_url", models.URLField(blank=True, null=True)),
                ("virtual_tour_url", models.URLField(blank=True, null=True)),
                ("documents", models.JSONField(blank=True, default=list)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("IN_REVIEW", "In Review"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RENTED", "Rented"),
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                            ("BOOKED", "Booked"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("inquiry_count", models.PositiveIntegerField(default=0)),
                ("favorite_count", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="accounts.ownerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "favorites",
            },
        ),
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("TITLE_DEED", "Title Deed"),
                            ("RENTAL_AGREEMENT", "Rental Agreement"),
                            ("SURVEY_PLAN", "Survey Plan"),
                            ("RATES", "Rates Payment"),
                            ("UTILITY_BILL", "Utility Bill"),
                            ("INSURANCE", "Insurance"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document", models.FileField(upload_to="properties/documents/")),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_documents",
                        to="properties.property",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "property_documents",
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="properties/images/")),
                ("is_main", models.BooleanField(default=False)),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_images",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["owner", "created_at"], name="properties_owner_i_b727a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["city", "property_type"], name="properties_city_a8f31b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["availability_status", "verification_status"],
                name="properties_availab_1ac6fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["rental_price"], name="properties_rental__99ecb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["bedrooms", "bathrooms"], name="properties_bedroom_2aae3d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "property")},
        ),
    ]
