# Generated by Django 5.2 on 2026-07-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="properties/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="propertyimage",
            unique_together={("property", "order")},
        ),
    ]
