# Generated by Django 5.2 on 2026-08-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_property_thumbnail_propertyimage_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="total_units",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
