# Generated by Django 5.2 on 2026-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_property_total_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="total_units",
            field=models.PositiveIntegerField(
                default=1, help_text="Total number of units in this property"
            ),
        ),
    ]
