# Generated by Django 5.2 on 2026-08-10 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_alter_property_total_units"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="available_units",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of available units"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="is_multi_unit",
            field=models.BooleanField(
                default=False, help_text="Does this property have multiple units?"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="total_units",
            field=models.PositiveIntegerField(
                default=1, help_text="Total number of units"
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unit_number",
                    models.CharField(help_text="e.g., A1, B2, 101, 202", max_length=50),
                ),
                ("floor_number", models.PositiveIntegerField(blank=True, null=True)),
                ("bedrooms", models.PositiveIntegerField()),
                ("bathrooms", models.PositiveIntegerField()),
                ("square_feet", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rental_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("features", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RENTED", "Rented"),
                            ("BOOKED", "Booked"),
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rented_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_units",
                "ordering": ["unit_number"],
                "unique_together": {("property_obj", "unit_number")},
            },
        ),
    ]
