# Generated by Django 5.2 on 2026-08-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_property_available_units_property_is_multi_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="cloudinary_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="properties/"),
        ),
    ]
