# Generated by Django 5.2 on 2026-08-16 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0007_fix_image_order_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="propertyimage",
            name="unique_property_image_order",
        ),
    ]
