# Generated by Django 5.2 on 2026-08-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0008_remove_propertyimage_unique_property_image_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="main_image_public_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="thumbnail_public_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="cloudinary_public_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
