# Generated by Django 5.2 on 2026-08-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0009_property_main_image_public_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="main_image_public_id",
        ),
        migrations.RemoveField(
            model_name="property",
            name="thumbnail_public_id",
        ),
        migrations.RemoveField(
            model_name="propertyimage",
            name="cloudinary_public_id",
        ),
        migrations.RemoveField(
            model_name="propertyimage",
            name="image",
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="main_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="thumbnail",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
