# Generated by Django 5.2 on 2026-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_remove_property_main_image_public_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="rental_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="security_deposit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="service_charge",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
