# Generated by Django 5.2.11 on 2026-09-16 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0012_property_land_reference_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="scouted_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "PROPERTY_SCOUT"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scouted_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
