# Generated by Django 5.2 on 2026-08-01 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
        ("properties", "0002_property_thumbnail_propertyimage_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_blocks",
            },
        ),
        migrations.CreateModel(
            name="UserMessageDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_message_deletions",
            },
        ),
        migrations.AddField(
            model_name="chatroom",
            name="is_muted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="muted_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_for_everyone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="reactions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="communications.message",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("PRIVATE", "Private"),
                    ("GROUP", "Group"),
                    ("PROPERTY_INQUIRY", "Property Inquiry"),
                ],
                default="PRIVATE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("FILE", "File"),
                    ("LOCATION", "Location"),
                    ("CONTACT", "Contact"),
                    ("SYSTEM", "System"),
                ],
                default="TEXT",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["is_active"], name="chat_rooms_is_acti_8486a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_deleted"], name="messages_is_dele_54348c_idx"
            ),
        ),
        migrations.AddField(
            model_name="chatblock",
            name="blocked",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_by_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatblock",
            name="blocker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usermessagedeletion",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="communications.message"
            ),
        ),
        migrations.AddField(
            model_name="usermessagedeletion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatblock",
            unique_together={("blocker", "blocked")},
        ),
        migrations.AlterUniqueTogether(
            name="usermessagedeletion",
            unique_together={("user", "message")},
        ),
    ]
