# Generated by Django 5.2 on 2026-07-30 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaseAgreementTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField()),
                (
                    "variables",
                    models.JSONField(
                        default=list, help_text="List of variables that can be replaced"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lease_templates",
            },
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "termination_notice_period",
                    models.PositiveIntegerField(
                        default=30, help_text="Termination notice period in days"
                    ),
                ),
                (
                    "late_payment_penalty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "lease_agreement",
                    models.FileField(blank=True, null=True, upload_to="leases/"),
                ),
                (
                    "signed_lease",
                    models.FileField(blank=True, null=True, upload_to="leases/signed/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_SIGNATURE", "Pending Signature"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to="properties.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leases",
            },
        ),
        migrations.CreateModel(
            name="LeaseRenewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_start_date", models.DateField()),
                ("new_end_date", models.DateField()),
                (
                    "new_monthly_rent",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewals",
                        to="tenants.lease",
                    ),
                ),
            ],
            options={
                "db_table": "lease_renewals",
            },
        ),
        migrations.CreateModel(
            name="TenantApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("intended_move_in_date", models.DateField()),
                (
                    "preferred_lease_duration",
                    models.PositiveIntegerField(help_text="Duration in months"),
                ),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("employment_status", models.CharField(max_length=50)),
                ("application_documents", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("owner_notes", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="properties.property",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenant_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["tenant", "status"], name="leases_tenant__efe78a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["property", "status"], name="leases_propert_49dbe5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["start_date", "end_date"], name="leases_start_d_825b01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantapplication",
            index=models.Index(
                fields=["tenant", "status"], name="tenant_appl_tenant__362372_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantapplication",
            index=models.Index(
                fields=["property", "status"], name="tenant_appl_propert_2b319f_idx"
            ),
        ),
    ]
