# Generated by Django 5.2 on 2026-08-11 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_property_available_units_property_is_multi_unit_and_more"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantapplication",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="properties.unit",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantapplication",
            index=models.Index(
                fields=["unit", "status"], name="tenant_appl_unit_id_8ebfb7_idx"
            ),
        ),
    ]
