# Generated by Django 5.2 on 2026-08-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_property_available_units_property_is_multi_unit_and_more"),
        ("tenants", "0002_tenantapplication_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leases",
                to="properties.unit",
            ),
        ),
    ]
