# Generated by Django 5.2 on 2026-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_lease_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="custom_lease_agreement",
            field=models.FileField(blank=True, null=True, upload_to="leases/custom/"),
        ),
        migrations.AddField(
            model_name="lease",
            name="use_custom_lease",
            field=models.BooleanField(default=False),
        ),
    ]
