# Generated by Django 5.2 on 2026-08-01 12:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="monthly_charge",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="platform_fee_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("3.00"), max_digits=5
            ),
        ),
    ]
