# Generated by Django 5.2 on 2026-08-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_subscriptionplan_monthly_charge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="owner_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payment",
            name="paystack_subaccount_code",
            field=models.CharField(
                blank=True, help_text="Paystack subaccount code", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="platform_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
