# Generated by Django 5.2 on 2026-09-10 09:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_admin_notes_user_registration_step_and_more"),
        ("payments", "0003_payment_owner_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="discounted_months",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="fee_mode",
            field=models.CharField(
                choices=[
                    ("PERCENTAGE", "Percentage platform fee"),
                    ("FLAT_RATE", "Flat monthly platform fee"),
                ],
                default="PERCENTAGE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="free_months",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="minimum_tenants",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="minimum_units",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic"),
                    ("PREMIUM", "Premium"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OwnerSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("discounted_months_remaining", models.PositiveIntegerField(default=0)),
                ("free_months_remaining", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("last_flat_fee_month", models.CharField(blank=True, max_length=7)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="accounts.ownerprofile",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_subscriptions",
                        to="payments.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "owner_subscriptions",
            },
        ),
    ]
