# Generated by Django 5.2 on 2026-09-10 10:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_alter_ownersubscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownersubscription",
            name="flat_fee_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
