# Generated by Django 5.2 on 2026-10-01 20:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_scoutpayout"),
        ("properties", "0013_property_scouted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="building_subscription_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="building_monthly_charge",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="building_threshold",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.CreateModel(
            name="BuildingSubscriptionCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_month", models.CharField(max_length=7)),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_subscription_charges",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "building_subscription_charges",
                "ordering": ["-billing_month"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="building_subscription_charge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="payments.buildingsubscriptioncharge",
            ),
        ),
        migrations.AddConstraint(
            model_name="buildingsubscriptioncharge",
            constraint=models.UniqueConstraint(
                fields=("property", "billing_month"),
                name="unique_property_building_charge_month",
            ),
        ),
    ]
