# Generated by Django 5.2 on 2026-10-01 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_payment_building_subscription_fee_and_more"),
        ("properties", "0013_property_scouted_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buildingsubscriptioncharge",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="buildingsubscriptioncharge",
            name="unique_property_building_charge_month",
        ),
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="building_monthly_charge",
            new_name="per_building_charge",
        ),
        migrations.RemoveField(
            model_name="buildingsubscriptioncharge",
            name="billing_month",
        ),
        migrations.AlterField(
            model_name="buildingsubscriptioncharge",
            name="property",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building_subscription_charge",
                to="properties.property",
            ),
        ),
    ]
