# Generated by Django 5.2 on 2026-10-02 03:54

from django.db import migrations, models


def promote_existing_building_fee_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("payments", "SubscriptionPlan")
    SubscriptionPlan.objects.using(schema_editor.connection.alias).filter(
        per_building_charge__gt=0,
    ).update(fee_mode="PER_BUILDING")


def restore_percentage_mode(apps, schema_editor):
    SubscriptionPlan = apps.get_model("payments", "SubscriptionPlan")
    SubscriptionPlan.objects.using(schema_editor.connection.alias).filter(
        fee_mode="PER_BUILDING",
    ).update(fee_mode="PERCENTAGE")


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0011_monthly_building_subscription_charges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="fee_mode",
            field=models.CharField(
                choices=[
                    ("PERCENTAGE", "Percentage platform fee"),
                    ("FLAT_RATE", "Flat monthly platform fee"),
                    ("PER_BUILDING", "Per-building fee"),
                ],
                default="PERCENTAGE",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            promote_existing_building_fee_plans,
            restore_percentage_mode,
        ),
    ]
