# Generated by Django 5.2 on 2026-08-22 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeoMeta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "url_path",
                    models.CharField(
                        help_text="URL path (e.g., /properties/)",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "page_title",
                    models.CharField(help_text="Browser tab title", max_length=200),
                ),
                (
                    "meta_title",
                    models.CharField(
                        help_text="SEO Title (max 60-70 chars)", max_length=70
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        help_text="SEO Description (max 160 chars)", max_length=160
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, help_text="Comma separated keywords", max_length=255
                    ),
                ),
                ("og_title", models.CharField(blank=True, max_length=200)),
                ("og_description", models.CharField(blank=True, max_length=200)),
                ("og_image", models.URLField(blank=True, null=True)),
                ("og_type", models.CharField(default="website", max_length=50)),
                (
                    "twitter_card",
                    models.CharField(default="summary_large_image", max_length=50),
                ),
                ("twitter_title", models.CharField(blank=True, max_length=200)),
                ("twitter_description", models.CharField(blank=True, max_length=200)),
                ("twitter_image", models.URLField(blank=True, null=True)),
                ("canonical_url", models.URLField(blank=True, null=True)),
                ("robots", models.CharField(default="index, follow", max_length=100)),
                ("structured_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SEO Meta",
                "verbose_name_plural": "SEO Meta",
                "db_table": "seo_meta",
            },
        ),
        migrations.CreateModel(
            name="SeoRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_path", models.CharField(max_length=500, unique=True)),
                ("new_path", models.CharField(max_length=500)),
                (
                    "redirect_type",
                    models.CharField(
                        choices=[
                            ("301", "Moved Permanently"),
                            ("302", "Found (Temporary)"),
                        ],
                        default="301",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "seo_redirects",
            },
        ),
        migrations.CreateModel(
            name="SeoRobots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_agent", models.CharField(default="*", max_length=100)),
                ("allow", models.TextField(blank=True)),
                ("disallow", models.TextField(blank=True)),
                ("sitemap", models.URLField(blank=True, null=True)),
                ("crawl_delay", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Robots.txt",
                "verbose_name_plural": "Robots.txt",
                "db_table": "seo_robots",
            },
        ),
        migrations.CreateModel(
            name="SeoSitemap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "priority",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
                ),
                (
                    "changefreq",
                    models.CharField(
                        choices=[
                            ("always", "Always"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("never", "Never"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "seo_sitemap",
            },
        ),
    ]
