# Generated by Django 5.2 on 2026-08-24 19:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "properties",
            "0011_alter_property_bathrooms_alter_property_bedrooms_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Report"),
                            ("WEEKLY", "Weekly Report"),
                            ("MONTHLY", "Monthly Report"),
                            ("QUARTERLY", "Quarterly Report"),
                            ("YEARLY", "Yearly Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("data", models.JSONField(default=dict)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PAGE_VIEW", "Page View"),
                            ("PROPERTY_VIEW", "Property View"),
                            ("APPLICATION_SUBMIT", "Application Submit"),
                            ("APPLICATION_APPROVE", "Application Approve"),
                            ("APPLICATION_REJECT", "Application Reject"),
                            ("PAYMENT_INITIATE", "Payment Initiate"),
                            ("PAYMENT_COMPLETE", "Payment Complete"),
                            ("PAYMENT_FAIL", "Payment Fail"),
                            ("LEASE_SIGN", "Lease Sign"),
                            ("LEASE_TERMINATE", "Lease Terminate"),
                            ("MAINTENANCE_REQUEST", "Maintenance Request"),
                            ("MAINTENANCE_RESOLVE", "Maintenance Resolve"),
                            ("MESSAGE_SENT", "Message Sent"),
                            ("USER_LOGIN", "User Login"),
                            ("USER_LOGOUT", "User Logout"),
                            ("USER_REGISTER", "User Register"),
                            ("PROPERTY_LIST", "Property List"),
                            ("UNIT_CREATE", "Unit Create"),
                            ("SEARCH", "Search"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referer", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.property",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"],
                        name="analytics_e_user_id_f87fa1_idx",
                    ),
                    models.Index(
                        fields=["property", "event_type"],
                        name="analytics_e_propert_6da708_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_e_created_3bce1d_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="analytics_e_session_b3cbf5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner Metrics"),
                            ("TENANT", "Tenant Metrics"),
                            ("PLATFORM", "Platform Metrics"),
                            ("PROPERTY", "Property Metrics"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_dashboard_metrics",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "metric_type"],
                        name="analytics_d_user_id_01d3b8_idx",
                    ),
                    models.Index(
                        fields=["generated_at"], name="analytics_d_generat_bb8f4c_idx"
                    ),
                ],
            },
        ),
    ]
