# Generated by Django 5.2 on 2026-08-25 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0006_user_admin_notes_user_registration_step_and_more"),
        (
            "properties",
            "0011_alter_property_bathrooms_alter_property_bedrooms_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAnalyticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("total_properties", models.PositiveIntegerField(default=0)),
                ("new_properties", models.PositiveIntegerField(default=0)),
                ("properties_views", models.PositiveIntegerField(default=0)),
                ("total_payments", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("new_applications", models.PositiveIntegerField(default=0)),
                ("messages_sent", models.PositiveIntegerField(default=0)),
                ("maintenance_requests", models.PositiveIntegerField(default=0)),
                ("chat_rooms_created", models.PositiveIntegerField(default=0)),
                (
                    "platform_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subscription_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analytics_daily_reports",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("TENANT", "Tenant Report"),
                            ("PROPERTY", "Property Report"),
                            ("PAYMENT", "Payment Report"),
                            ("MAINTENANCE", "Maintenance Report"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("metrics", models.JSONField(default=list)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("chart_type", models.CharField(default="line", max_length=20)),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "schedule_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_generated", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_reports",
                        to="accounts.ownerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "saved_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "format",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("PDF", "PDF"), ("EXCEL", "Excel")],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="reports/exports/"
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_exports",
                        to="accounts.ownerprofile",
                    ),
                ),
                (
                    "saved_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="analytics.savedreport",
                    ),
                ),
            ],
            options={
                "db_table": "report_exports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PAGE_VIEW", "Page View"),
                            ("PROPERTY_VIEW", "Property View"),
                            ("APPLICATION_SUBMIT", "Application Submit"),
                            ("APPLICATION_APPROVE", "Application Approve"),
                            ("APPLICATION_REJECT", "Application Reject"),
                            ("PAYMENT_INITIATE", "Payment Initiate"),
                            ("PAYMENT_COMPLETE", "Payment Complete"),
                            ("PAYMENT_FAIL", "Payment Fail"),
                            ("LEASE_SIGN", "Lease Sign"),
                            ("LEASE_TERMINATE", "Lease Terminate"),
                            ("MAINTENANCE_REQUEST", "Maintenance Request"),
                            ("MAINTENANCE_RESOLVE", "Maintenance Resolve"),
                            ("MESSAGE_SENT", "Message Sent"),
                            ("USER_LOGIN", "User Login"),
                            ("USER_LOGOUT", "User Logout"),
                            ("USER_REGISTER", "User Register"),
                            ("PROPERTY_LIST", "Property List"),
                            ("UNIT_CREATE", "Unit Create"),
                            ("SEARCH", "Search"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referer", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.property",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"],
                        name="analytics_e_user_id_f87fa1_idx",
                    ),
                    models.Index(
                        fields=["property", "event_type"],
                        name="analytics_e_propert_6da708_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_e_created_3bce1d_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="analytics_e_session_b3cbf5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("REVENUE", "Revenue"),
                            ("APPLICATIONS", "Applications"),
                            ("TENANTS", "Tenants"),
                            ("MAINTENANCE", "Maintenance"),
                            ("PROPERTY_VIEWS", "Property Views"),
                            ("UNIT_OCCUPANCY", "Unit Occupancy"),
                            ("PLATFORM_FEES", "Platform Fees"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("date", models.DateField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_metrics",
                        to="accounts.ownerprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_metrics",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_metrics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["owner", "metric_type", "date"],
                        name="analytics_m_owner_i_6d9730_idx",
                    ),
                    models.Index(
                        fields=["property", "metric_type", "date"],
                        name="analytics_m_propert_704c74_idx",
                    ),
                ],
            },
        ),
    ]
