# Generated by Django 5.2 on 2026-08-24 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsmetric",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
