# Generated by Django 5.2 on 2026-08-24 16:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_admin_notes_user_registration_step_and_more"),
        ("analytics", "0001_initial"),
        (
            "properties",
            "0011_alter_property_bathrooms_alter_property_bedrooms_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("widgets", models.JSONField(blank=True, default=list)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analytics_dashboards",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("PROPERTY_VIEWS", "Property Views"),
                            ("APPLICATIONS", "Applications"),
                            ("PAYMENTS", "Payments"),
                            ("MAINTENANCE", "Maintenance"),
                            ("TENANTS", "Tenants"),
                            ("REVENUE", "Revenue"),
                            ("PLATFORM_FEES", "Platform Fees"),
                            ("USER_ENGAGEMENT", "User Engagement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_metrics",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("PROPERTY", "Property Report"),
                            ("TENANT", "Tenant Report"),
                            ("FINANCIAL", "Financial Report"),
                            ("MAINTENANCE", "Maintenance Report"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "format",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("CSV", "CSV"), ("EXCEL", "Excel")],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("file", models.FileField(blank=True, null=True, upload_to="reports/")),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "schedule_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_generated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analytics_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="pageview",
            name="user",
        ),
        migrations.RenameField(
            model_name="dailyanalyticsreport",
            old_name="platform_revenue",
            new_name="platform_fees",
        ),
        migrations.RemoveField(
            model_name="dailyanalyticsreport",
            name="subscription_revenue",
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["related_object_type", "related_object_id"],
                name="analytics_u_related_f712ef_idx",
            ),
        ),
        migrations.AddField(
            model_name="analyticsdashboard",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_dashboard",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="analyticsmetric",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.ownerprofile",
            ),
        ),
        migrations.AddField(
            model_name="analyticsmetric",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="analyticsreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="PageView",
        ),
        migrations.AddIndex(
            model_name="analyticsmetric",
            index=models.Index(
                fields=["metric_type", "date"], name="analytics_m_metric__94423b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsmetric",
            index=models.Index(
                fields=["owner", "metric_type"], name="analytics_m_owner_i_62734d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsmetric",
            index=models.Index(
                fields=["property", "metric_type"],
                name="analytics_m_propert_4eae52_idx",
            ),
        ),
    ]
