# Generated by Django 5.2 on 2026-08-26 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        (
            "properties",
            "0011_alter_property_bathrooms_alter_property_bedrooms_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.unit",
            ),
        ),
    ]
