# Generated by Django 5.2 on 2026-07-30 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_application_updates", models.BooleanField(default=True)),
                ("email_payment_notifications", models.BooleanField(default=True)),
                ("email_maintenance_updates", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=True)),
                ("email_marketing", models.BooleanField(default=False)),
                ("sms_application_updates", models.BooleanField(default=False)),
                ("sms_payment_notifications", models.BooleanField(default=True)),
                ("sms_maintenance_updates", models.BooleanField(default=False)),
                ("sms_messages", models.BooleanField(default=True)),
                ("push_application_updates", models.BooleanField(default=True)),
                ("push_payment_notifications", models.BooleanField(default=True)),
                ("push_maintenance_updates", models.BooleanField(default=True)),
                ("push_messages", models.BooleanField(default=True)),
                ("daily_digest", models.BooleanField(default=True)),
                ("weekly_digest", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                (
                    "quiet_hours_start",
                    models.TimeField(blank=True, default="22:00", null=True),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, default="07:00", null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference_obj",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPLICATION", "Application Update"),
                            ("PAYMENT", "Payment Notification"),
                            ("MAINTENANCE", "Maintenance Update"),
                            ("MESSAGE", "New Message"),
                            ("LEASE", "Lease Update"),
                            ("REMINDER", "Reminder"),
                            ("SYSTEM", "System Notification"),
                            ("PROMOTION", "Promotion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.CharField(blank=True, max_length=50)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("sent_email", models.BooleanField(default=False)),
                ("sent_sms", models.BooleanField(default=False)),
                ("sent_push", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_7336fd_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a4dd5c_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_19df93_idx",
                    ),
                ],
            },
        ),
    ]
